# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-20 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_auto_20190720_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsumption',
            name='consumption',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
